# Generated by Django 5.0.6 on 2024-06-14 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_evolution', to='api.species')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('happiness', models.IntegerField(default=1)),
                ('hit_points', models.IntegerField(default=1)),
                ('attack', models.IntegerField(default=1)),
                ('defense', models.IntegerField(default=1)),
                ('special_attack', models.IntegerField(default=1)),
                ('special_defense', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('held_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='held_item', to='api.item')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_items', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='api.species')),
            ],
        ),
    ]
