# Generated by Django 4.2.13 on 2024-06-11 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution', to='api.species')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('happiness', models.IntegerField(default=1)),
                ('hit_points', models.IntegerField(default=1)),
                ('attack', models.IntegerField(default=1)),
                ('defense', models.ImageField(default=1, upload_to='')),
                ('special_attack', models.IntegerField(default=1)),
                ('special_defense', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('held_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_item', to='api.item')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='api.species')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
