# Generated by Django 4.2.13 on 2024-06-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='normal', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='api.species'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='poke_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poke_type', to='api.poketype'),
        ),
    ]
