# Generated by Django 4.2.13 on 2024-06-20 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_poketype_alter_pokemon_species_pokemon_poke_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='gender',
            field=models.CharField(default='non-gendered', max_length=10),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poketype',
            name='name',
            field=models.CharField(default='Normal', max_length=100, null=True),
        ),
    ]
