# Generated by Django 4.2.13 on 2024-06-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pokemon_description_alter_pokemon_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokadex_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
