# Generated by Django 4.2.13 on 2024-06-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pokemon_held_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='held_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='held_item', to='api.item'),
        ),
    ]
