# Generated by Django 4.2.13 on 2024-06-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pokemon_pokadex_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokadex_id',
            new_name='pokedex_id',
        ),
    ]
