# Generated by Django 4.2.13 on 2024-06-12 05:43

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trainer',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
